#!/usr/bin/env python3
"""Census the look direction of the whole NISAR beta archive.

`verify_lookdir.py` inspects a hand-picked set of granules in depth. This
script answers the broader question those results raise: **is any real NISAR
acquisition right-looking?**

It enumerates every NISAR L2 GUNW beta granule via CMR, groups them by
(track, pass direction), and probes one granule per group for
``science/LSAR/identification/lookDirection``. Only ~0.26 MB is fetched per
probe, so the full census costs well under a gigabyte.

A sample of the GSLC/GCOV/RSLC beta collections is probed too, to check
whether the answer is specific to the interferogram product or holds across
the mission.

The result is written to ``reports/archive_survey.md``.
"""

from __future__ import annotations

import argparse
import collections
import sys
import time
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from typing import Optional

import fsspec
import h5py
import requests

from verify_lookdir import LOOK_DIR_DATASET, scrub

CMR = 'https://cmr.earthdata.nasa.gov/search/granules.json'
ASF = 'https://nisar.asf.earthdatacloud.nasa.gov/NISAR'

GUNW_COLLECTION = 'NISAR_L2_GUNW_BETA_V1'
OTHER_COLLECTIONS = {
    'NISAR_L2_GSLC_BETA_V1': 'GSLC',
    'NISAR_L2_GCOV_BETA_V1': 'GCOV',
    'NISAR_L1_RSLC_BETA_V1': 'RSLC',
}

# Small blocks keep each probe to a few hundred KB: we only need one scalar.
PROBE_BLOCK_SIZE = 64 * 1024


def list_granules(short_name: str, page_size: int = 2000, max_pages: int = 20) -> list[str]:
    """Enumerate granule IDs in a CMR collection.

    Args:
        short_name: CMR collection short name.
        page_size: Granules requested per page.
        max_pages: Safety cap on pagination.

    Returns:
        Sorted granule IDs.
    """
    session = requests.Session()
    out: list[str] = []
    for page in range(1, max_pages + 1):
        resp = session.get(
            CMR, params={'short_name': short_name, 'page_size': page_size, 'page_num': page}, timeout=120
        )
        resp.raise_for_status()
        entries = resp.json()['feed']['entry']
        out += [e['title'] for e in entries]
        if len(entries) < page_size:
            break
    return sorted(out)


def track_pass(granule_id: str) -> tuple[str, str]:
    """Extract (track, pass) from a NISAR granule ID.

    Args:
        granule_id: e.g. ``NISAR_L2_PR_GUNW_003_159_A_022_...``.

    Returns:
        Tuple of track number and pass letter (``'A'`` or ``'D'``).
    """
    parts = granule_id.split('_')
    return parts[5], parts[6]


def probe_look(short_name: str, granule_id: str, retries: int = 3) -> Optional[str]:
    """Read just ``lookDirection`` from a remote granule.

    Args:
        short_name: CMR collection short name (also the ASF path segment).
        granule_id: Granule to probe.
        retries: Attempts before giving up.

    Returns:
        The look direction, or None if every attempt failed.
    """
    url = f'{ASF}/{short_name}/{granule_id}/{granule_id}.h5'
    for attempt in range(1, retries + 1):
        try:
            resp = requests.get(url, stream=True, allow_redirects=True, timeout=90)
            resp.raise_for_status()
            final = resp.url
            resp.close()
            handle = fsspec.filesystem('http').open(final, 'rb', block_size=PROBE_BLOCK_SIZE)
            with h5py.File(handle, 'r') as h:
                look = h[LOOK_DIR_DATASET][()].decode()
            handle.close()
            return look
        except Exception as exc:  # noqa: BLE001 - retry transient network faults
            if attempt == retries:
                print(f'    {granule_id[:40]}: {scrub(exc)}', file=sys.stderr)
            else:
                time.sleep(3 * attempt)
    return None


def build_report(
    gunw: list[tuple[tuple[str, str], Optional[str], str]],
    others: dict[str, list[Optional[str]]],
    total_granules: int,
    elapsed: float,
) -> str:
    """Render the census report.

    Args:
        gunw: Per-(track, pass) probe results as ((track, pass), look, granule_id).
        others: Look directions sampled per non-GUNW product type.
        total_granules: Number of GUNW granules in the collection.
        elapsed: Wall-clock seconds for the census.

    Returns:
        The report as a markdown string.
    """
    counts = collections.Counter(look or 'unreadable' for _, look, _ in gunw)
    rights = [(c, g) for c, look, g in gunw if look == 'Right']
    read = sum(1 for _, look, _ in gunw if look)

    lines = [
        '# NISAR archive look-direction census',
        '',
        'Generated by `survey_archive.py` (`make survey`). Companion to',
        '[`lookdir_verification.md`](lookdir_verification.md); evidence for',
        '[RAiDER issue #676](https://github.com/dbekaert/RAiDER/issues/676).',
        '',
        '## Question',
        '',
        'The verification run finds real NISAR GUNWs to be left-looking. Is *any*',
        'real NISAR acquisition right-looking?',
        '',
        '## Answer',
        '',
        f'**No.** Across `{GUNW_COLLECTION}` — {total_granules} granules, grouped into',
        f'{len(gunw)} distinct (track, pass) combinations, one probed per group:',
        '',
        '| lookDirection | (track, pass) groups |',
        '|---|---|',
    ]
    for look, n in counts.most_common():
        lines.append(f'| {"**" + look + "**" if look != "unreadable" else look} | {n} |')

    lines += [
        '',
        f'Right-looking groups found: **{len(rights)} of {read} readable**.',
        '',
        'The same holds outside the interferogram product — sampling other NISAR beta',
        'collections across distinct tracks:',
        '',
        '| product | probed | result |',
        '|---|---|---|',
    ]
    for prod, looks in sorted(others.items()):
        ok = [x for x in looks if x]
        summary = ', '.join(f'{k}×{v}' for k, v in collections.Counter(ok).most_common()) or 'unreadable'
        lines.append(f'| {prod} | {len(ok)} | {summary} |')

    lines += [
        '',
        '## Why this matters for #676',
        '',
        'NISAR is a left-looking mission. RAiDER hardcodes `right` for ray-traced runs',
        "(the run config's `look_dir` never reaches `Raytracing`), so the look direction is",
        'wrong for **every** NISAR product, not just some of them.',
        '',
        'The one right-looking product in `lookdir_verification.md` is the JPL sample-suite',
        'granule, which is ALOS-1 PALSAR surrogate data rather than a NISAR acquisition. It is',
        'kept as a control: it proves the reader and the geometric check discriminate both',
        'values instead of always reporting `Left`.',
        '',
        '## Method',
        '',
        f'Granules are enumerated via CMR, grouped by (track, pass), and one per group is',
        f'probed with a {PROBE_BLOCK_SIZE // 1024} KB-block `fsspec` HTTP handle, so `h5py` reads only the',
        'HDF5 metadata needed for one scalar (~0.26 MB per granule rather than ~2 GB).',
        '',
        f'Census wall-clock: {elapsed / 60:.0f} min.',
        '',
        '```bash',
        'make survey',
        '```',
        '',
    ]
    if rights:
        lines += ['## Right-looking groups', '', '| track | pass | granule |', '|---|---|---|']
        lines += [f'| {c[0]} | {c[1]} | `{g}` |' for c, g in rights]
        lines.append('')
    return '\n'.join(lines)


def main() -> int:
    """Run the census and write the report.

    Returns:
        Process exit code; 0 unless nothing could be read.
    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--workers', type=int, default=8, help='concurrent probes')
    parser.add_argument(
        '--sample-others', type=int, default=5, help='granules to probe per non-GUNW collection'
    )
    parser.add_argument(
        '--out',
        type=Path,
        default=Path(__file__).parent / 'reports' / 'archive_survey.md',
        help='path of the markdown report to write',
    )
    args = parser.parse_args()
    t0 = time.time()

    print(f'Enumerating {GUNW_COLLECTION} via CMR...', flush=True)
    names = list_granules(GUNW_COLLECTION)
    groups: dict[tuple[str, str], list[str]] = collections.defaultdict(list)
    for n in names:
        groups[track_pass(n)].append(n)
    combos = sorted(groups)
    print(f'  {len(names)} granules, {len(combos)} (track, pass) groups', flush=True)

    def probe_group(combo: tuple[str, str]) -> tuple[tuple[str, str], Optional[str], str]:
        granule = sorted(groups[combo])[0]
        return combo, probe_look(GUNW_COLLECTION, granule), granule

    gunw: list[tuple[tuple[str, str], Optional[str], str]] = []
    with ThreadPoolExecutor(max_workers=args.workers) as pool:
        for i, out in enumerate(pool.map(probe_group, combos), 1):
            gunw.append(out)
            if out[1] != 'Left':
                print(f'  [{i}/{len(combos)}] track {out[0][0]} {out[0][1]} -> {out[1]}', flush=True)
            elif i % 40 == 0:
                print(f'  ...{i}/{len(combos)}', flush=True)

    others: dict[str, list[Optional[str]]] = {}
    for short_name, prod in OTHER_COLLECTIONS.items():
        print(f'Sampling {prod}...', flush=True)
        picks: dict[str, str] = {}
        for g in list_granules(short_name, page_size=60, max_pages=1):
            picks.setdefault(track_pass(g)[0], g)
        chosen = list(picks.values())[: args.sample_others]
        with ThreadPoolExecutor(max_workers=args.workers) as pool:
            others[prod] = list(pool.map(lambda g: probe_look(short_name, g), chosen))
        print(f'  {prod}: {collections.Counter(x for x in others[prod] if x)}', flush=True)

    if not any(look for _, look, _ in gunw):
        print('Nothing could be read.', file=sys.stderr)
        return 2

    elapsed = time.time() - t0
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(build_report(gunw, others, len(names), elapsed))
    print(f'\nWrote {args.out} ({len(combos)} groups, {elapsed / 60:.0f} min)')
    return 0


if __name__ == '__main__':
    sys.exit(main())
